name = "v2ex-push-service"
main = "src/index.ts"
compatibility_date = "2024-02-04"
node_compat = true

[triggers]
crons = ["*/15 * * * *"] # Every 15 minutes

[[kv_namespaces]]
binding = "V2EX_PUSH_KV"
id = "954cd9fe3c9e42b38b9b526dfb9dbec3"
preview_id = "a1c1c9bf8fc64c44986f03a1a0b6ad66"

[vars]
# FIREBASE_SERVICE_ACCOUNT_JSON = "set via wrangler secret put FIREBASE_SERVICE_ACCOUNT_JSON"
# ADMIN_SECRET = "set via wrangler secret put ADMIN_SECRET"
