name: Publish to App Store and Google Play

on:
  push:
    tags:
      - 'v*'  # 推送带 v 前缀的标签时触发 (例如 v1.0.0)
  workflow_dispatch:  # 支持手动触发

jobs:
  build-react:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.setup_version.outputs.BUILD_VERSION }}
      display_version: ${{ steps.setup_version.outputs.DISPLAY_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup version
        id: setup_version
        run: |
          echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV
          echo "DISPLAY_VERSION=$VERSION" >> $GITHUB_ENV
          # Convert to build number: 1.0.1 -> 1000001
          BUILD_VERSION=$(echo $VERSION | sed -e 's/\./ /g' | xargs printf "%d%03d%03d")
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build React app
        run: |
          npm install
          npm run build
        working-directory: ./src/V2ex.Maui2.IonicApp

      - uses: actions/upload-artifact@v6
        with:
          name: react-build
          path: ./src/V2ex.Maui2.IonicApp/dist


  # Android 构建
  build-android:
    runs-on: macos-latest
    needs: build-react
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Install Android workload
        run: |
          dotnet workload install maui 
          dotnet workload install android 

      - name: Download React build artifact
        uses: actions/download-artifact@v7
        with:
          name: react-build
          path: ./src/V2ex.Maui2.App/Resources/Raw/wwwroot

      - name: Retrieve the secret and decode it to a file
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > src/V2ex.Maui2.App/keystore.jks

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/V2ex.Maui2.App

      - name: Build and publish Android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          BUILD_VERSION: ${{ needs.build-react.outputs.build_version }}
          DISPLAY_VERSION: ${{ needs.build-react.outputs.display_version }}
        run: |
          dotnet publish -f net10.0-android -c Release \
           -p:AndroidKeyStore=true \
           -p:AndroidSigningKeyStore=keystore.jks \
           -p:AndroidSigningKeyAlias=v2ex_key \
           -p:AndroidSigningStorePass=$KEYSTORE_PASSWORD \
           -p:AndroidSigningKeyPass=$KEY_PASSWORD \
           -p:ApplicationVersion=$BUILD_VERSION \
           -p:ApplicationDisplayVersion=$DISPLAY_VERSION
        working-directory: ./src/V2ex.Maui2.App

      - name: Upload Android AAB to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: './src/V2ex.Maui2.App/bin/Release/net10.0-android/**/*.aab'

  # # iOS 构建
  # build-ios:
  #   runs-on: macos-latest
  #   needs: build-react
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '10.0.x'

  #     - uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: latest

  #     - name: Install iOS workload
  #       run: |
  #         dotnet workload install maui 
  #         dotnet workload install ios 

  #     - name: Restore dependencies
  #       run: dotnet restore
  #       working-directory: ./src/V2ex.Maui2.App

  #     - name: Setup provisioning profile
  #       env:
  #         PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
  #         PROVISIONING_PROFILE_PATH: ${{ runner.temp }}/V2ex.mobileprovision
  #       run: |
  #         echo "$PROVISIONING_PROFILE_BASE64" | base64 -d > $PROVISIONING_PROFILE_PATH
  #         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  #         cp $PROVISIONING_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

  #     - name: Install Apple Certificate
  #       uses: apple-actions/import-codesign-certs@v1
  #       with:
  #         p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
  #         p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      
  #     - name: Install Provisioning Profile
  #       uses: apple-actions/download-provisioning-profiles@v1
  #       with:
  #         bundle-id: "tech.zb.v2ex.maui.app"
  #         # profile-type: "IOS_APP_STORE"
  #         issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
  #         api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
  #         api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

  #     - name: Build iOS
  #       env:
  #         BUILD_VERSION: ${{ needs.build-react.outputs.build_version }}
  #         DISPLAY_VERSION: ${{ needs.build-react.outputs.display_version }}
  #       run: |
  #         dotnet publish -f net10.0-ios -c Release \
  #           -p:ApplicationVersion=$BUILD_VERSION \
  #           -p:ApplicationDisplayVersion=$DISPLAY_VERSION \
  #           -p:ArchiveOnBuild=true \
  #           -p:RuntimeIdentifier=ios-arm64 \
  #           -p:CodesignKey="${{ secrets.APPLE_SIGNING_IDENTITY }}" \
  #           -p:CodesignProvision="${{ secrets.APPLE_PROVISIONING_PROFILE_NAME }}" \
  #       working-directory: ./src/V2ex.Maui2.App

  #     - name: Upload to TestFlight
  #       uses: apple-actions/upload-testflight-build@v1
  #       with:
  #         app-path: "src/V2ex.Maui2.App/bin/Release/net10.0-ios/ios-arm64/publish/V2ex.Maui2.App.ipa"
  #         issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
  #         api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
  #         api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

  #     - name: Upload a Build Artifact
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: ios-build
  #         path: "src/V2ex.Maui2.App/bin/Release/net10.0-ios/ios-arm64/publish/*.ipa"
